#! /bin/sh

# autostart applications
xsetroot -cursor_name left_ptr
bash $HOME/scripts/wallpaper.sh &
bash $HOME/scripts/xmod.sh &
~/.config/polybar/launch.sh
picom -f &
fcitx5 &

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V
bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color   "#6f6f6f"
bspc config active_border_color   "#6f6f6f"
bspc config focused_border_color  "#9862fb"
bspc config presel_feedback_color "$color1"
bspc config focus_follows_pointer true
bspc config bottom_padding        5
bspc config top_padding           30
bspc config left_padding          5
bspc config right_padding         5
