#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x dunst > /dev/null || dunst &

bash $HOME/scripts/wallpaper.sh &
$HOME/.config/polybar/launch.sh
picom -b

bspc monitor -d I II III IV V
bspc config border_width         2
bspc config window_gap          10
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color   "#908caa"
bspc config active_border_color   "#6e6a86"
bspc config focused_border_color  "#9ccfd8"
bspc config presel_feedback_color "#81A1C1"
bspc config bottom_padding        5
bspc config top_padding           30
bspc config left_padding          5
bspc config right_padding         5

bspc rule -a Thunar state=floating
